import {
  BarChart3,
  Banknote,
  BadgeDollarSign,
  Binary,
  Braces,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Calculator,
  ChartArea,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartNoAxesCombined,
  ChartPie,
  ChartScatter,
  ChartSpline,
  ClipboardCheck,
  ClipboardList,
  Code2,
  Columns3,
  Compass,
  ContactRound,
  Crosshair,
  CircleDollarSign,
  Database,
  DatabaseBackup,
  DatabaseZap,
  Download,
  Factory,
  FileText,
  FileChartColumn,
  FileChartLine,
  FileSpreadsheet,
  Files,
  Folder,
  FolderCog,
  FolderGit2,
  FolderKanban,
  FolderOpen,
  Globe,
  Globe2,
  Goal,
  Handshake,
  HardDrive,
  Hexagon,
  Kanban,
  Layers3,
  Landmark,
  LineChart,
  ListChecks,
  Locate,
  LocateFixed,
  Map,
  MapPin,
  MapPinHouse,
  MapPinned,
  Milestone,
  Navigation,
  Package,
  PackageOpen,
  Pin,
  PieChart,
  Presentation,
  ReceiptText,
  Rows3,
  Ruler,
  Route,
  ScanSearch,
  Search,
  Server,
  ShoppingBag,
  ShoppingCart,
  Sigma,
  Signpost,
  Sparkles,
  Sprout,
  Store,
  TableProperties,
  Table2,
  Target,
  Trash2,
  Upload,
  Users,
  UsersRound,
  WalletCards,
  Warehouse,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { PublicToolIconName } from './types';

const TOOL_ICONS: Record<PublicToolIconName, LucideIcon> = {
  store: Store,
  'map-pin': MapPin,
  sprout: Sprout,
  'bar-chart': BarChart3,
  'chart-area': ChartArea,
  database: Database,
  hexagon: Hexagon,
  map: Map,
  trash: Trash2,
  ruler: Ruler,
  zap: Zap,
  'globe-2': Globe2,
  globe: Globe,
  'line-chart': LineChart,
  target: Target,
  users: Users,
  'pie-chart': PieChart,
  'file-spreadsheet': FileSpreadsheet,
  files: Files,
  calculator: Calculator,
  search: Search,
  upload: Upload,
  download: Download,
  'file-text': FileText,
  'table-2': Table2,
  'layers-3': Layers3,
  'building-2': Building2,
  'briefcase-business': BriefcaseBusiness,
  'shopping-bag': ShoppingBag,
  'scan-search': ScanSearch,
  route: Route,
  navigation: Navigation,
  'map-pinned': MapPinned,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'chart-column': ChartColumn,
  'folder-cog': FolderCog,
  wrench: Wrench,
  bot: Bot,
  sparkles: Sparkles,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-kanban': FolderKanban,
  'folder-git-2': FolderGit2,
  workflow: Workflow,
  kanban: Kanban,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  goal: Goal,
  milestone: Milestone,
  boxes: Boxes,
  package: Package,
  'package-open': PackageOpen,
  'database-zap': DatabaseZap,
  'database-backup': DatabaseBackup,
  server: Server,
  'hard-drive': HardDrive,
  'table-properties': TableProperties,
  'rows-3': Rows3,
  'columns-3': Columns3,
  'file-chart-column': FileChartColumn,
  'file-chart-line': FileChartLine,
  'chart-spline': ChartSpline,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-scatter': ChartScatter,
  sigma: Sigma,
  binary: Binary,
  braces: Braces,
  'code-2': Code2,
  'locate-fixed': LocateFixed,
  locate: Locate,
  crosshair: Crosshair,
  pin: Pin,
  'map-pin-house': MapPinHouse,
  landmark: Landmark,
  warehouse: Warehouse,
  signpost: Signpost,
  compass: Compass,
  waypoints: Waypoints,
  handshake: Handshake,
  'shopping-cart': ShoppingCart,
  'receipt-text': ReceiptText,
  'badge-dollar-sign': BadgeDollarSign,
  'circle-dollar-sign': CircleDollarSign,
  'wallet-cards': WalletCards,
  banknote: Banknote,
  presentation: Presentation,
  factory: Factory,
  'users-round': UsersRound,
  'contact-round': ContactRound,
};

export default function PublicToolIcon({
  name,
}: {
  name: PublicToolIconName;
}) {
  const Icon = TOOL_ICONS[name]
  return <Icon aria-hidden="true" className="h-5 w-5" strokeWidth={1.7} />;
}
